server:
  port: 18000
logging:
  file: ./log/customer.log
  pattern:
    console: "%date{yyyy-MM-dd HH:mm:ss.SSS} -%5level [customer][%15.15thread] %-40.40logger{39} [%6line]: %msg%n"
spring:
  h2:
    console:
      enabled: true
  datasource:
    url: jdbc:h2:mem:customer
    username: sa
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: create
    show-sql: true

customer-properties:
  onemap-url: https://developers.onemap.sg/commonapi/search