server:
  port: 18000

spring:
  h2:
    console:
      enabled: true
  datasource:
    url: jdbc:h2:mem:customer
    username: sa
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: create
    show-sql: true

customer-properties:
  onemap-url: https://developers.onemap.sg/commonapi/search