version: "3"
services:

  eureka:
    build: ./eureka
    image: "xushikuan/sillyhat.cloud.eureka:master"
    ports:
      - 8761:8761
    deploy:
      replicas: 1

  zuul:
    build: ./zuul
    image: "xushikuan/sillyhat.cloud.zuul:master"
    deploy:
      replicas: 1
    ports:
      - 8080:8080

  customer:
    build: ./customer
    image: "xushikuan/sillyhat.cloud.customer:master"
    deploy:
      replicas: 1

  web-app:
    build: ./web-app
    image: "xushikuan/sillyhat.cloud.web-app:master"
    deploy:
      replicas: 1