version: "3"
services:

  eureka:
    build: ./eureka
    image: "xushikuan/sillyhat.cloud.eureka"
    ports:
      - 8761:8761
    deploy:
      replicas: 1

  zuul:
    build: ./zuul
    image: "xushikuan/sillyhat.cloud.zuul"
    deploy:
      replicas: 1
    ports:
      - 8080:8080

  customer:
    build: ./customer
    image: "xushikuan/sillyhat.cloud.customer"
    deploy:
      replicas: 1