server:
  port: 18010

feign:
  client:
    config:
      feignName:
        connectTimeout: 5000
        readTimeout: 5000
        loggerLevel: full
        #errorDecoder: com.example.SimpleErrorDecoder
        #retryer: com.example.SimpleRetryer
        requestInterceptors:
          - com.sillyhat.cloud.webapp.config.TokenInterceptorBackups
